### PR TITLE
Better Readability On Code Blocks Close #31

### LINKED ISSUE #31: Request Option to Disable strikethrough style on deleted code
#### What's the issue:

 Strikethrough style on deleted code is hard to read.  Any way to disable this style?
#### Steps to reproduce:

View code chances
#### Screenshots:

screen shot 2016-09-30 at 10 11 42 am
#### Solutions:

Add an option to disable this style.  Couldn't find it in CSS
#### What version is affected by this problem:

GitHub Dark v2.5.0

### PR DESCRIPTION
**Pull request by lacostenycoder**
#### What's the issue:

Difficulty reading deleted code with line-through style noted in issue:  https://github.com/cquanu/github-dark/issues/31

#### What's fixed:
 
Removed line-through style.  Changed background colors on code blocks for better readability.  

#### Screenshots:

screen shot 2016-11-02 at 11 39 31 am

Remove line-through style  on .blob-code-deletion class.
Modify background colors on .blob-code-deletion and
.blob-code-adition classes.

### CODE REVIEW

**Comment by lacostenycoder** [comment]
@snowe2010 Can you post a screenshot to see how it will look?

**Comment by snowe2010** [comment]
@lacostenycoder 
new colors

**Comment by snowe2010** [comment]
just slightly brighter.

**Comment by lacostenycoder** [comment]
@snowe2010  Looks good to me!  Should I fix merge conflicts and make the changes or?

**Comment by snowe2010** [comment]
Get rid of the min.css because I'll just recompile that after I merge a bunch of other prs, and fix the merge conflicts in the `.css` and I'll go ahead and merge!

**Comment by lacostenycoder** [comment]
@snowe2010 requested changes made!

**Pull request merged**
