### PR TITLE
Fix #107 Issue comments have dark text on dark background

### LINKED ISSUE #107: Issue comments have dark text on dark background
#### What's the issue:

 
Issue comments have dark text color on dark background.
 
#### Steps to reproduce:

Latest version of GitHub Dark on Firefox with GitHub.com

#### Screenshots:

Screenshot 2019-09-07 at 12 10 38

#### What version is affected by this problem:

```
Firefox 70.0b3 (64-bit)
Version 1.0.17
Last Updated September 7, 2019
```

### PR DESCRIPTION
**Pull request by scottmcgowan**
#### What's the issue:
#107  comments have dark text on dark background

#### What's fixed:
Adds `color: var(--primary-text-color)` to `.timeline-comment`

#### Screenshots:
Before:
image
image

After:
image
image

### CODE REVIEW

**Comment by snowe2010** [comment]
Thanks for the fix! Sorry for the delay!

**Comment by Mikaela** [comment]
Should the version number be increased? Stylus refused to detect and install the fix until I visited the install page again and clicked force reinstall 2.6.9 -> 2.6.9

**Comment by snowe2010** [comment]
Yes I am having that issue as well. Technically it shouldn't need that, as it worked fine for a long time. I think I'll need to build in an action that does so.

**Comment by snowe2010** [comment]
@Mikaela I have now automated the version update using Github Actions so the version should update automatically on every merge from now on!

**Pull request merged**
