### PR TITLE
Update github-dark.css

### PR DESCRIPTION
**Pull request by rainautumn**
#### Screenshots:
2016-06-21-004107_985x355_scrot

Contributors colour

### CODE REVIEW

**Comment by cquanu** [comment]
Hi @rainautumn I'm seeing some problem on my side.
nothing

And please use other color instead of red. Appreciate your help!

**Comment by rainautumn** [comment]
i think green so bad, and you? 
2016-06-24-084724_741x202_scrot
...
`.day {
    filter: hue-rotate(180deg) invert(90%) saturate(120%);

}

    .legend{
            filter: hue-rotate(180deg) invert(90%) saturate(120%);
    }`

tested only on firefox.

**Comment by rainautumn** [comment]
2016-06-24-090214_229x185_scrot
2016-06-24-090158_713x50_scrot
:D realy?!

**Comment by cquanu** [comment]
@rainautumn I believe there isn't any problem on Firefox. But it's just not showing on Chrome.

**Comment by cquanu** [comment]
Can you try these color instead? [Optical Fibre color]
fibre color

**Comment by cquanu** [comment]
Btw what's that for?
capture

**Comment by rainautumn** [comment]
>Btw what's that for?
https://cquanu.github.io/

**Comment by cquanu** [comment]
@rainautumn I know. i mean why you screenshot it

**Comment by rainautumn** [comment]
links confused
twitter -> fb
fb -> twitter
```
.day {
    filter: hue-rotate(-50deg) invert(90%) saturate(150%);

}

    .legend{
            filter: hue-rotate(-50deg) invert(90%) saturate(150%);
    }
    ```
2016-06-24-102445_755x217_scrot

**Comment by cquanu** [comment]
Hahaha wow 👍 Thanks for spotting XD

**Comment by rainautumn** [comment]
i think webkit eat it 
не знаю английский. прости
```
.day {
    filter: hue-rotate(-50deg) invert(100%) saturate(150%);
    fill-opacity: 0.8;

}

    .legend{
            filter: hue-rotate(-50deg) invert(100%) saturate(150%);
            fill-opacity: 0.8;
    }
```

**Comment by rainautumn** [comment]
2016-06-24-103117_1034x375_scrot

**Comment by cquanu** [comment]
Зажигалка синий?

**Comment by rainautumn** [comment]
>Зажигалка синий?
It sounds very funny! :D

**Comment by cquanu** [comment]
Future feature. Not now

**Pull request closed without merging**
