### PR TITLE
Fix for Contribution Activity on profile page

### PR DESCRIPTION
**Pull request by lauraerinmann**

### CODE REVIEW

**Comment by Nikitaw99** [comment]
Screenshots or it didn't happen.

**Comment by lauraerinmann** [comment]
asrequested

**Comment by cquanu** [comment]
@lauraerinmann Sorry do you have the URL link for this?

**Comment by lauraerinmann** [comment]
[example for cquanu](https://github.com/alexnassif)

**Comment by cquanu** [comment]
Finally i see! Thanks. This fix will be pushed in the next release.

fix_contribution_activity

**Comment by cquanu** [comment]
#3 Fixed in [v1.4.0](https://github.com/cquanu/github-dark/releases/tag/v1.4.0)
Thanks for the help.

**Pull request closed without merging**
